"$schema" = "./node_modules/wrangler/config-schema.json"
name = "4d-ai-web"
main = ".open-next/worker.js"
compatibility_date = "2025-05-25"
compatibility_flags = ["nodejs_compat"]

[[services]]
binding = "DICTIONARY_API"
service = "4dai88-dictionary-api"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
